### ISSUE TITLE
When unzipping, it does not pull files from the Documents folder

### ISSUE THREAD

**Issue by alexardishev** [bimspot/bcf-toolkit#13]
If there is a document inside bcfzip, then it is not exported. Why is that? Or should I additionally specify something?

**Comment by balintbendebimspot** [comment]
Hey @alexardishev 
This has been not added to the toolkit yet. Will be fixed soon.

**Comment by alexardishev** [comment]
> Привет@alexardishev Это еще не добавлено в набор инструментов. Скоро будет исправлено.

thx

**Comment by alexardishev** [comment]
Hello! Probably you can say me wnich deadline you`ll fixing that bug?

**Comment by balintbendebimspot** [comment]
Hey @alexardishev!

We are focusing on the fixes of known issues, like handling the internal documents. Soon the release is out which will contain the fix. It is expected in the upcoming weeks.

**Comment by balintbendebimspot** [comment]
Hey @alexardishev 
Now in the latest release, the toolkit is storing the internal documents data for BCF3.0. Please have a look. Your feedback is appreciated!
